weshoulddeletethe login page
puppetup/plenty-of-hanks pull request #40
Opened 2022-08-08 23:00 UTC by zzcipod

debug

2022-08-08 23:00 UTC, zzcipod commented
?

2022-08-08 23:37 UTC, zzcipod reviewed
debug

2022-08-08 23:37 UTC, zzcipod reviewed
000

2022-08-09 04:31 UTC, zzcipod commented
111

2022-08-09 15:56 UTC, prsoulman requested changes

2022-08-09 15:56 UTC, prsoulman commented on client/src/pages/Login.js
> +  debugger
please take out debugger

2022-08-09 15:56 UTC, prsoulman commented on client/src/utils/auth.js
> +    window.location.assign('/selectMovies');
This is approved

2022-08-09 16:05 UTC, closed without merging